### ISSUE TITLE
Results on "Search users" have incorrect buttons after you've opened your own profile

### ISSUE THREAD

**Issue by stupidbaldbaby** [BetterMeower/BetterMeower-Svelte#10]
Instead of the "add to groupchat" and "report" buttons, it instead will show "account settings" and "logout" buttons, but only if you've opened up your profile.

![image](https://github.com/BetterMeower/BetterMeower-Svelte/assets/139823344/9031ed9b-5d3a-4899-b24e-a332191cbe35)

**Comment by JoshAtticus** [comment]
@mdwalters can you look into this?

**Comment by theycallhermax** [comment]
> @mdwalters can you look into this?

on it

**Comment by JoshAtticus** [comment]
ClassicClient is now deprecated
